
class IconName {
  static const String home = 'assets/icons/home.svg';
  static const String chart = 'assets/icons/chart.svg';
  static const String creat = 'assets/icons/creat.svg';
  static const String profile = 'assets/icons/profile.svg';

  // static const AssetImage scan = AssetImage('assets/icons/scan.png');
  // static const AssetImage chatQuoteLine =
  //     AssetImage('assets/icons/chat-quote-line.png');
  // static const AssetImage contactsLine =
  //     AssetImage('assets/icons/contacts-line.png');
  // static const AssetImage mentalHealthLine =
  //     AssetImage('assets/icons/mental-health-line.png');  
  // static const AssetImage profileLine =
  //     AssetImage('assets/icons/profile-line.png');
  // static const AssetImage projector2Line =
  //     AssetImage('assets/icons/projector-2-line.png');
}

/// Flutter icons AppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///

// class AppIcons {
//   AppIcons._();

//   static const _kFontFam = 'AppIcons';
//   static const String? _kFontPkg = null;

//   static const IconData contact = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData email = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData github = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData logout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData menuleft = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData peace = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rate = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData trophyoutline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData web = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData code = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }

